### ISSUE TITLE
DB directory change and caida file

### ISSUE THREAD

**Issue by lisaens** [netsage-project/netsage-pipeline#50]
For 1.2.6,
I've moved the maxmind and scireg db's to a new directory which makes more sense than the old one.
Old: /var/cache/grnoc/netsage/
New: /var/lib/grnoc/netsage/

Also, you will now have to get the caida db (csv file) and put it there too.

Cron files have been renamed, so watch out for that.

**Comment by safaci2000** [comment]
This was fixed with the PR #52
